name: fourth_pyramid_task
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.0
  google_fonts: ^4.0.4
  image_picker: ^0.8.7+5
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  qr_code_scanner: ^1.0.1
  scan: ^1.6.0
  share: ^2.0.4
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.17

flutter_native_splash:
 color: '#FFFFFF'
 android_12:
   color: '#FFFFFF'
 android: true
 ios: true
 fullscreen: false

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
